### ISSUE TITLE
Add open-source library MoSDH to the library listing

### ISSUE THREAD

**Issue by MoSDH** [modelica/old.modelica.org#19]
We would like to have https://github.com/MoSDH/MoSDH listed on modelica.org/libraries.

**Comment by dietmarw** [comment]
Done. It should appear in a couple of days.

**Comment by JFormhals** [comment]
Tanks a lot

**Comment by JFormhals** [comment]
Hi @dietmarw, could you add the library description please? Don't know if it was missing in the initial upload, but now it's definitely there. Cheers, Julian

**Comment by dietmarw** [comment]
I needed to refork it siden you seem to have removed the repo and recreated it again. The new one has the description string so that should now also come up in the listing (takes at least 24 hours).
