### ISSUE TITLE
Add open-source library EHPTlib to the library listing

### ISSUE THREAD

**Issue by ceraolo** [modelica/old.modelica.org#26]
We would like to have https://github.com/ceraolo/EHPTlib/ listed on modelica.org/libraries.

As a description I propose:
"Free library to simulate power trains of electric and hybrid vehicles. "

**Comment by dietmarw** [comment]
@ceraolo Thank you for the contribution. However, that repository is missing a LICENSE file and the library itself does not state under which license the library can be used. This basically forbids ANY code usage other than just looking at it. Could you please supply a license? The most natural choices would be BSD (like MSL) or MPL (copy-left but allows coupling with other commercial libraries). 

As for the description, simply put it in the "About" field of your GitHub project. That information will then be mirrored to the modelica.org/libries page.

**Comment by ceraolo** [comment]
I've just realised that an open-dource named "EHPT" is already listed in the page https://modelica.org/libraries.html. Probably I managed to do this a few years ago, and then completely forgot about it.

That one should be deleted because it is an older version of EHPTlib. Sorry for the inconvenience.

Note that At those times I used a github with a strange name "max-privato". Now I use my surname "ceraolo".

In case of need, I can sign in with "max-ceraolo" and ask for deletion of the old EHPT, once the new one is uploaded.

**Comment by dietmarw** [comment]
I've now completed the following tasks
- [ ] delete modelica-3rdparty/EHPT
- [ ] fork [ceraolo/EHPTlib](https://github.com/ceraolo/EHPTlib) to [modelica-3rdparty/EHPTlib](https://github.com/modelica-3rdparty/EHPTlib)
- [ ] set up nightly sync of [ceraolo/EHPTlib](https://github.com/ceraolo/EHPTlib) to [modelica-3rdparty/EHPTlib](https://github.com/modelica-3rdparty/EHPTlib)

@ceraolo you can now safely delete [max-privato/EHPT](https://github.com/max-privato/EHPT)

**Comment by ceraolo** [comment]
I checked today.
EHPTlib is there, thank you.
However, it is also there EHPT. Did something get wrong with the removal?

**Comment by dietmarw** [comment]
I've now deleted the [modelica-3rdparty/EHPT](https://github.com/modelica-3rdparty/EHPT) fork. So it should get removed from the listing soon.
