### ISSUE TITLE
404 error Modelica Conference website 2017

### ISSUE THREAD

**Issue by MABackoffice** [modelica/old.modelica.org#6]
The link to the 12th Modelica Conference Program shows a 404 error. 
I tried to make changes f59c871 , but apparently it did not work.
How can this be fixed?

**Comment by sjoelund** [comment]
I guess revert that commit. There is no ProgramViewing.pdf in the 2017 repository:
```
martin@ws:~/dev/ModelicaConference2017$ find . -name "*.pdf" | grep -i program
./proceedings/html/Program.pdf
```

**Comment by MABackoffice** [comment]
I wouldn't have made those changes (f59c871) if it was working before. I tried to revert that commit anyhow.
Before the changes of f59c871 it looked like this:
![grafik](https://user-images.githubusercontent.com/40261100/120481767-bbf52e00-c3b0-11eb-9476-89df86ebaa87.png)
The link https://2017.international.conference.modelica.org/proceedings/html/ProgramViewing.pdf showed an error and is still showing an error, but if I use https://2017.international.conference.modelica.org/proceedings/html/Program.pdf it seems to work fine.

**Comment by sjoelund** [comment]
Thanks. I've fixed that at the source: https://github.com/modelica/ModelicaConference2017/commit/baa440e860e6beca023753095b052a61ffc472f9

This repository does not affect what is stored in the other domains. And I guess there was some copy-paste error for that README:md. Thanks for finding that. Now f59c871 should be reverted as well, I think.

**Comment by MABackoffice** [comment]
Thank you for fixing the source and explaining.
I made these changes 653433c with links like before f59c871 .
Now it works fine.
